In [2]:
import numpy as np


1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.



In [4]:
np.zeros((3,3),dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [5]:
np.random.randint(1,11, size=(5,5))


array([[ 5,  8,  1,  6,  7],
       [ 3, 10,  4,  3,  2],
       [ 3,  3,  5,  3,  1],
       [ 2,  5,  8, 10,  6],
       [ 5,  2,  4,  3,  1]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


In [6]:
np.random.rand(4,4)

array([[0.60764773, 0.84814958, 0.15488405, 0.87501508],
       [0.17474229, 0.36139983, 0.77949119, 0.87754309],
       [0.34288012, 0.3181853 , 0.05579861, 0.64815529],
       [0.01817733, 0.42642198, 0.16033195, 0.5045677 ]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [7]:
d1=np.random.randint(1,11, 5)
d2=np.random.randint(1,11, 5)
d1,d2

(array([8, 9, 1, 3, 1]), array([9, 4, 3, 9, 2]))

In [8]:
d1+d2

array([17, 13,  4, 12,  3])

In [9]:
d1-d2

array([-1,  5, -2, -6, -1])

In [10]:
d1*d2

array([72, 36,  3, 27,  2])

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [11]:
e1=np.random.randint(1,11, 7)
e2=np.random.randint(1,11, 7)
e1, e2

(array([ 3,  8,  5,  1,  5,  5, 10]), array([10,  4,  7,  5, 10,  2,  1]))

In [12]:
np.dot(e1,e2)

172

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [13]:
f1=np.random.randint(1,11, size=(2,2))
f2=np.random.randint(1,11, size=(2,3))
f1, f2

(array([[ 6, 10],
        [ 5,  8]]),
 array([[ 1,  9,  9],
        [10,  3,  3]]))

In [14]:
np.dot(f1,f2)

array([[106,  84,  84],
       [ 85,  69,  69]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [15]:
g=np.random.randint(1,11, size=(3,3))
g

array([[ 9,  3,  2],
       [ 4, 10,  9],
       [ 5, 10,  9]])

In [16]:
np.linalg.inv(g)

array([[-4.44089210e-16, -1.00000000e+00,  1.00000000e+00],
       [ 1.28571429e+00,  1.01428571e+01, -1.04285714e+01],
       [-1.42857143e+00, -1.07142857e+01,  1.11428571e+01]])

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [17]:
h=np.random.rand(4,4)
h

array([[0.2543412 , 0.26760558, 0.68705097, 0.89096883],
       [0.23004985, 0.13892599, 0.88299472, 0.92171467],
       [0.26899669, 0.28976419, 0.80831985, 0.34266498],
       [0.35005656, 0.88620221, 0.36055862, 0.06274496]])

In [18]:
np.transpose(h)

array([[0.2543412 , 0.23004985, 0.26899669, 0.35005656],
       [0.26760558, 0.13892599, 0.28976419, 0.88620221],
       [0.68705097, 0.88299472, 0.80831985, 0.36055862],
       [0.89096883, 0.92171467, 0.34266498, 0.06274496]])

In [19]:
h.T

array([[0.2543412 , 0.23004985, 0.26899669, 0.35005656],
       [0.26760558, 0.13892599, 0.28976419, 0.88620221],
       [0.68705097, 0.88299472, 0.80831985, 0.36055862],
       [0.89096883, 0.92171467, 0.34266498, 0.06274496]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [20]:
i1=np.random.randint(1,11, size=(3,4))
i2=np.random.randint(1,11, 4)
np.dot(i1,i2)

array([30, 52, 79])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [21]:
j1=np.random.rand(2,3)
j2=np.random.random(3)
np.dot(j1,j2)

array([1.1906293 , 0.47707955])

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [22]:
k1=np.random.randint(1,11, size=(2,2))
k2=np.random.randint(1,11, size=(2,2))
k1*k2

array([[64, 54],
       [27,  7]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [24]:
l1=np.random.randint(1,11, size=(2,2))
l2=np.random.randint(1,11, size=(2,2))
np.dot(l1,l2)

array([[94, 16],
       [53,  8]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [29]:
m=np.random.randint(1,101, size=(5,5))
print(m)
np.sum(m)

[[37 98 26 98 36]
 [12  1 56 49 35]
 [53 93 84 35 65]
 [14 41 20 49  6]
 [63 98 82 38 46]]


1235

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [43]:
n1=np.random.randint(1,11, size=(4,4))
n2=np.random.randint(1,11, size=(4,4))
n1, n2

(array([[5, 6, 6, 6],
        [4, 5, 2, 8],
        [9, 5, 6, 7],
        [2, 2, 2, 3]]),
 array([[ 3,  2,  8,  7],
        [10, 10,  1,  5],
        [ 8,  5,  9,  4],
        [ 5,  2,  8, 10]]))

In [45]:
n1-n2

array([[ 2,  4, -2, -1],
       [-6, -5,  1,  3],
       [ 1,  0, -3,  3],
       [-3,  0, -6, -7]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [71]:
o1=np.random.rand(3,3)
o1

array([[0.43976419, 0.32255037, 0.22321909],
       [0.20929067, 0.20344196, 0.20082621],
       [0.04778368, 0.57317555, 0.03224723]])

In [66]:
o2=o1.sum(axis=1).reshape(-1,1)
o2

array([[1.89130544],
       [2.04840221],
       [1.53233036]])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [83]:
p=np.random.randint(1,11, size=(3,4))
print(p)
print()
print(p*p)

[[ 1  9  2  5]
 [ 3  2  8 10]
 [10  4  1 10]]

[[  1  81   4  25]
 [  9   4  64 100]
 [100  16   1 100]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [97]:
r=np.random.randint(1,51, 4)
print(r)
print()
print((r**0.5).round(2))

[11 40  7 11]

[3.32 6.32 2.65 3.32]
